Added proxy config

diff --git a/.sti/bin/assemble b/.sti/bin/assemble
--- a/.sti/bin/assemble
+++ b/.sti/bin/assemble
@@ -1,4 +1,35 @@
-#!/bin/sh
-#
+#!/bin/bash
+
+# Prevent running assemble in builders different than official STI image.
+# The official nodejs:0.10-onbuild already run npm install and use different
+# application folder.
+[ -d "/usr/src/app" ] && exit 0
+
+set -e
+
+if [ "$1" = "-h" ]; then
+  exec /usr/local/sti/usage
+fi
+
+# FIXME: Linking of global modules is disabled for now as it causes npm failures
+#        under RHEL7
+# Global modules good to have
+# npmgl=$(grep "^\s*[^#\s]" ../etc/npm_global_module_list | sort -u)
+# Available global modules; only match top-level npm packages
+#global_modules=$(npm ls -g 2> /dev/null | perl -ne 'print "$1\n" if /^\S+\s(\S+)\@[\d\.-]+/' | sort -u)
+# List all modules in common
+#module_list=$(/usr/bin/comm -12 <(echo "${global_modules}") | tr '\n' ' ')
+# Link the modules
+#npm link $module_list
+
+echo "---> Installing application source"
+cp -Rf /tmp/src/. ./
+chgrp -R 0 ./
+chmod -R g+rw ./
+
+echo "---> Building your Node application from source"
+npm config set ${CUSTOM_PROXY_HOST}:${CUSTOM_PROXY_PORT}
+npm config set ${CUSTOM_PROXY_HOST}:${CUSTOM_PROXY_PORT}
+npm install -d
 
 
